/// <reference types="Cypress" />

it('Replenishment of mobile phone number', () => {
    cy.visit('https://next.privat24.ua/mobile/?lang=en')
        .get('[data-qa-node="phone-number"]')
        .type('686979712')
        .get('[data-qa-node="amount"]')
        .type('1')
        .get('[data-qa-node="numberdebitSource"]')
        .type('4552331448138217')
        .get('[data-qa-node="expiredebitSource"]')
        .type('0524')
        .get('[data-qa-node="cvvdebitSource"]')
        .type('111')
        .get('[data-qa-node="submit"]')
        .focus()
        .wait(3000)
        .get('[data-qa-node="firstNamedebitSource"]')
        .type('taras')
        .get('[data-qa-node="lastNamedebitSource"]')
        .type('shevchenko')
        .wait(3000)
        .get('[data-qa-node="submit"]')
        .click()
        .get('[data-qa-node="card"]')
        .should('have.text', '4552 **** **** 8217')
        .get('[data-qa-node="amount"]')
        .should('have.text', '1')
        .get('[data-qa-node="currency"]')
        .eq(0)
        .should('contain.text', 'UAH')
        .get('span[data-qa-node="commission"]')
        .should('have.text', '2')
        .get('[data-qa-node="currency"]')
        .eq(1)
        .should('contain.text', 'UAH')
})

it.only("Money transfer between foreign cards", () => {
    cy.visit('https://next.privat24.ua/money-transfer/card/?lang=en')
        .get('[data-qa-node="numberdebitSource"]')
        .type('4552331448138217')
        .get('[data-qa-node="expiredebitSource"]')
        .type('0524')
        .get('[data-qa-node="cvvdebitSource"]')
        .type('111')
        .wait(2000)
        .get('[data-qa-node="firstNamedebitSource"]')
        .type('taras')
        .get('[data-qa-node="lastNamedebitSource"]')
        .type('shevchenko')
        .get('[data-qa-node="numberreceiver"]')
        .type('5309233034765085')
        .wait(2000)
        .get('[data-qa-node="firstNamereceiver"]')
        .type('taras')
        .get('[data-qa-node="lastNamereceiver"]')
        .type('shevchenko')
        .get('[data-qa-node="amount"]')
        .type('300')
        .get('[data-qa-node="toggle-comment"]')
        .click()
        .get('[placeholder="Your comment"]')
        .type('Cypress test')
        .get('button[type="submit"]')
        .wait(2000)
        .click()
        .get('[data-qa-node="payer-card"]')
        .should('have.text', '4552 3314 4813 8217')
        .get('[data-qa-node="receiver-card"]')
        .should('have.text', '5309 2330 3476 5085')
        .get('[data-qa-node="payer-amount"]')
        .should('have.text', '300 UAH')
        .get('[data-qa-node="payer-currency"]')
        .should('have.text', '86.60 UAH')
        .get('[data-qa-node="total"]')
        .find('b')
        .should('contain.text', '386.60')
        .get('[data-qa-node="comment"]')
        .should('have.text', 'Cypress test')

})